version: '3.8'

services:

  postgres:
    image: postgres:16

    container_name: smartfinance-db

    environment:
      POSTGRES_DB: smartfinance
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data


  app:
    build: .

    container_name: smartfinance-app

    depends_on:
      - postgres

    ports:
      - "8082:8081"

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/smartfinance
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password

volumes:
  postgres_data: